# Auto-generated OCR mapping
# Generated by ocr_scraper.py
# Format: "language": "api_url"

mappings = {
    "Hindi": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/6711fe751595b8ffe97adc1f",
    "English": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f420802ae0a1948845594",
    "Bengali": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f5c8902ae0a19488455a6",
    "Assamese": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f64af02ae0a19488455ae",
    "Gujarati": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f64c202ae0a19488455af",
    "Kannada": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f64db02ae0a19488455b0",
    "Malayalam": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f64f302ae0a19488455b1",
    "Marathi": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f650402ae0a19488455b2",
    "Punjabi": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f651a02ae0a19488455b3",
    "Tamil": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f65df02ae0a19488455b4",
    "Telugu": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f65f502ae0a19488455b5",
    "Bodo": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f791d02ae0a19488455ba",
    "Dogri": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f793002ae0a19488455bb",
    "Kashmiri": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f794a02ae0a19488455bc",
    "Konkani": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f796002ae0a19488455bd",
    "Maithili": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f799c02ae0a19488455be",
    "Manipuri": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f79b502ae0a19488455bf",
    "Nepali": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f79c802ae0a19488455c0",
    "Odia": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f79d702ae0a19488455c1",
    "Sanskrit": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f79ec02ae0a19488455c2",
    "Santali": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f7a0002ae0a19488455c3",
    "Sindhi": "https://canvas.iiit.ac.in/sandboxbeprod/check_ocr_status_and_infer/687f7a1302ae0a19488455c4",
}
