# Auto-generated ASR mapping
# Generated by asr_scraper.py
# Format: "language": "api_url"

mappings = {
    "Hindi": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/67100d22a0397bc812dacb27",
    "English": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/67127dcbb1a6984f0c5e7d35",
    "Telugu": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/6807e9185343f3e4aea3b32e",
    "Urdu": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/67b8413f9c21bec07537674c",
    "Marathi": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/6834159c620e7a7dd24ec497",
    "Bengali": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/68341884620e7a7dd24ec498",
    "Kannada": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/6834189e620e7a7dd24ec499",
    "Malayalam": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/683418b8620e7a7dd24ec49a",
    "Bhojpuri": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/683418df620e7a7dd24ec49b",
    "Gujarati": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/683418f5620e7a7dd24ec49c",
    "Odia": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/68341929620e7a7dd24ec49d",
    "Punjabi": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/68341945620e7a7dd24ec49e",
    "Tamil": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/6834195d620e7a7dd24ec49f",
    "Sanskrit": "https://canvas.iiit.ac.in/sandboxbeprod/infer_asr/68341979620e7a7dd24ec4a0",
}
