#!/usr/bin/env python3
"""
TTS Scraper - Extract TTS models from JSON file and create mapping

This script reads a JSON file containing model information and extracts
TTS models to create a mapping dictionary like the one in mapping.py.
The mapping format is: source_language: api_url
"""

import json
import sys
from typing import Dict, List, Any


def load_json_file(file_path: str) -> List[Dict[str, Any]]:
    """
    Load JSON data from file.
    
    Args:
        file_path (str): Path to the JSON file
        
    Returns:
        List[Dict[str, Any]]: List of model data dictionaries
        
    Raises:
        FileNotFoundError: If the JSON file doesn't exist
        json.JSONDecodeError: If the JSON file is malformed
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            data = json.load(file)
            # Handle both single object and array formats
            if isinstance(data, dict):
                return [data]
            elif isinstance(data, list):
                return data
            else:
                raise ValueError("JSON file must contain an object or array of objects")
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON format in '{file_path}': {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading file '{file_path}': {e}")
        sys.exit(1)


def extract_tts_models(data: List[Dict[str, Any]]) -> Dict[str, str]:
    """
    Extract TTS models from the data and create a mapping.
    
    Args:
        data (List[Dict[str, Any]]): List of model data dictionaries
        
    Returns:
        Dict[str, str]: Mapping of source_language to api_url for TTS models
    """
    tts_mapping = {}
    
    for item in data:
        # Check if this is a TTS model
        if item.get('model_type') == 'tts':
            source_language = item.get('source_language')
            api_url = item.get('api_url')
            
            # Only add if both source_language and api_url exist
            if source_language and api_url:
                tts_mapping[source_language] = api_url
                print(f"Found TTS model: {source_language} -> {api_url}")
            else:
                model_name = item.get('model_name', 'Unknown')
                print(f"Warning: TTS model '{model_name}' missing source_language or api_url")
    
    return tts_mapping


def save_mapping_to_file(mapping: Dict[str, str], output_file: str = "tts_mapping.py") -> None:
    """
    Save the mapping dictionary to a Python file.
    
    Args:
        mapping (Dict[str, str]): The TTS mapping dictionary
        output_file (str): Output file name (default: "tts_mapping.py")
    """
    with open(output_file, 'w', encoding='utf-8') as file:
        file.write("# Auto-generated TTS mapping\n")
        file.write("# Generated by tts_scraper.py\n\n")
        file.write("mappings = {\n")
        
        for language, url in mapping.items():
            file.write(f'    "{language}": "{url}",\n')
        
        file.write("}\n")
    
    print(f"Mapping saved to '{output_file}'")


def print_mapping_stats(mapping: Dict[str, str]) -> None:
    """
    Print statistics about the extracted mapping.
    
    Args:
        mapping (Dict[str, str]): The TTS mapping dictionary
    """
    print(f"\n--- TTS Mapping Statistics ---")
    print(f"Total TTS models found: {len(mapping)}")
    print(f"Languages supported: {', '.join(sorted(mapping.keys()))}")


def main():
    """
    Main function to orchestrate the TTS extraction process.
    """
    # Default input file name
    input_file = "../filled_megathon_models_68ea6227b93e3bec901fd8d7_1760194626.json"
    output_file = "tts_mapping.py"
    
    # Allow command line arguments
    if len(sys.argv) > 1:
        input_file = sys.argv[1]
    if len(sys.argv) > 2:
        output_file = sys.argv[2]
    
    print(f"Reading JSON data from: {input_file}")
    
    # Load and process the JSON data
    data = load_json_file(input_file)
    print(f"Loaded {len(data)} items from JSON file")
    
    # Extract TTS models
    tts_mapping = extract_tts_models(data)
    
    if not tts_mapping:
        print("No TTS models found in the JSON file.")
        return
    
    # Print statistics
    print_mapping_stats(tts_mapping)
    
    # Save to file
    save_mapping_to_file(tts_mapping, output_file)
    
    print(f"\nSuccess! TTS mapping extracted and saved to '{output_file}'")


if __name__ == "__main__":
    main()